routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::prefix('admin')->middleware(['auth', 'CheckIfAdmin'])->group( function () {
    Route::get('/', 'AdminController@index')->name('admin.index');
    Route::get('/users', 'AdminController@users')->name('admin.users');
    Route::post('/users', 'AdminController@store')->name('admin.store');
    Route::put('/users/{id}', 'AdminController@update')->name('admin.update');
}); 

Route::resource('posts', 'PostController');

app/Post.php
<?php

namespace App;
use App\Tag;

use Illuminate\Database\Eloquent\Model;

class Post extends Model
{
    protected $fillable = ['title', 'body', 'image'];

    public function user() {

        return $this->belongsTo('App\User', 'user_id');
    }

    public function tags() {

        return $this->belongsToMany('App\Tag', 'tag_post');
    }

    public function scopeSearch($query, $s) {

        return $query->where('title', 'like', '%' .$s. '%')
            ->orWhere('body', 'like', '%' .$s. '%');
    }

}

app/Http/Controllers/PostController.php
<?php

namespace App\Http\Controllers;

use App\Post;
use App\Tag;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Gate;


class PostController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */

    public function __construct() {
        $this->middleware('auth')->except('index', 'show');
    }

    public function index(Request $request)
    {   
        $s = $request->input('s');

        $posts = Post::orderBy('created_at', 'desc')->search($s)->paginate('3');

        return view('posts.index', compact('posts', 's'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(Tag $tags)
    {
        $tags = Tag::orderBy('created_at', 'desc')->get();

        return view('posts.create', compact('tags'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

        $request->validate([
            'title' => ['required'],
            'body' => ['required'],
            'image' => ['required', 'image', 'max:2048'],
            'tags' => ['required', 'exists:tags,id']
        ]);

        $post = new Post;
        $post->title = $request->input('title');
        $post->body = $request->input('body');
        $post->user_id = auth()->id();
        
        if ($request->hasFile('image')) {
            $imgName = md5(date('Y-m-d'). "_" . microtime()) . 
            "." . $request->file('image')->getClientOriginalExtension();
            $post->image = $imgName;
        }

         if ($post->save()) {
            $post->tags()->attach(explode(',',$request->input('tags')));
            $request->image->move(public_path('images/posts'), $imgName);
            $x = session()->flash('success','Post created!');

            return response()->json([
                        'status' => 200,
                        'sms' => 'Post Created!',
                        'x'
                    ]);
        }   else {
            return response()->json([
                'status' => 500,
                'sms' => 'Something went wrong!'
            ]);
        }

    }


    /**
     * Display the specified resource.
     *
     * @param  \App\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function show(Post $post)
    {
        return view('posts.show', compact('post'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function edit(Post $post)
    {
        $tags = Tag::get();

        if (Gate::allows('posts.edit', $post)) {
            return view('posts.edit', compact('post','tags'));
        }
        else {
            abort(404);
        }
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $post)
    {
        if (! request()->ajax() && 
        !request()->isSecure()) {
            return response()->json(['error' => 'Failed to update.'], 500);
        }

        $request->validate([
            'title' => ['required'],
            'body' => ['required'],
            'tags' => ['required', 'exists:tags,id']
        ]);

        if ($request->hasFile('image')) {
            $request->validate([
                'image' => ['image', 'max:2048']  
            ]);

            $imgName = md5(date('Y-m-d'). "_" . microtime()) .
            "." . $request->file('image')->getClientOriginalExtension();
        }

            $x = Post::findOrFail($post);
            $x->title = $request->title;
            $x->body = $request->body;
        
        if ($request->hasFile('image')) {
            $x->image = $imgName;
        }

        if ($x->save()) {
            
            if ($request->hasFile('image')) {
                $request->image->move(public_path('images/posts'), $imgName);
            }

            $x->tags()->detach();
            $x->tags()->attach(explode(',',$request->input('tags')));
            $x = session()->flash('success','Post Updated!');

            return response()->json([
                'status' => 200,
                'sms' => 'Successfully Edited!!',
                'x'
            ]);
        } 
        else {
            return response()->json([
                'status' => 500,
                'sms' => 'Something went wrong!!'
            ]);
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function destroy(Post $post)
    {
        if (Gate::allows('posts.edit', $post)) {

            $post->tags()->detach();

            $post->delete($post);
            
            return redirect()->route('posts.index')->with('success', 'Post Deleted!');
        }
        else {
            abort(404);
        }
        

    }
}

resources/views/posts/create.blade.php
@extends('layouts.app')

@section('content')

@include('layouts.messages')

<div class="container">
    <form method="POST" id="createForm" action="" enctype="multipart/form-data">
        {{ csrf_field() }}
        <div class="form-group">
            <label for="title">Post Title</label>
            <input type="text" class="form-control" id="title" name="title" aria-describedby="title-Help" placeholder="Post title...">
            <div class="invalid-feedback" id="err-title" role="alert"></div>            
            <small id="titleHelp" class="form-text text-muted">Title of the post.</small>
        </div>
        <div class="form-group">
            <label for="body">Post Body</label>
            <textarea class="form-control" id="body" name="body" rows="3"></textarea>
            <div class="invalid-feedback" id="err-body" role="alert"></div>
            <small id="titleHelp" class="form-text text-muted">Post content.</small>
        </div>
        <div class="form-group">
            <input type="file" id="image" name="image" />
            <div class="invalid-feedback" id="err-image" role="alert"></div>
        </div>
        <div class="form-group row">
                {{-- POST TAGS --}}
                <div class="col-lg-12">
                    <strong class="text-muted mb-3 mt-4 d-block">Tags:</strong>

                    @if( !count($tags) )
                    <h6>No Tags found.</h6>
                    @else
                    <div class="custom-control custom-checkbox custom-control-inline">
                        <input type="checkbox" id="select_all" class="custom-control-input text-lowercase">
                        <label class="custom-control-label text-uppercase" for="select_all"><strong>select all</strong></label>
                    </div>
                    @foreach( $tags as $tag )
                    <div class="custom-control custom-checkbox custom-control-inline">
                        <input type="checkbox" name="tags" class="custom-control-input text-lowercase row_check"
                            id="{{ "tag-" . utf8_decode($tag->name) }}" value="{{ $tag->id }}"
                            {{ $loop->last ? 'checked' : '' }}
                            data-id="{{$tag->id}}">
                        <label class="custom-control-label text-lowercase" for="{{ "tag-". utf8_decode($tag->name) }}">
                        {{ utf8_decode($tag->name) }}</label>
                    </div>
                    @endforeach
                    @endif
                    <div class="invalid-feedback" id="err-tags" role="alert"></div>
                </div>
            </div>
        <div class="form-group">
            <a class="btn btn-danger" href="{{URL::previous()}}">Cancel</a>
            <button type="submit" id="submitBtn" class="btn btn-primary">
                {{ __('Submit') }}
            </button>
        </div>
    </form>
</div>

<script>

$(document).ready( () => {

    $('#select_all').on('click', (e) => {        
        $('.row_check').prop('checked', $(e.target).prop('checked'));
    })

    $('.row_check').on('click', () => {
        if ($('.row_check:checked').length == $('.row_check').length) {
            $('#select_all').prop('checked', true)
        } else {
            $('#select_all').prop('checked', false)
        }
    })

    document.getElementById('createForm').addEventListener('submit', (e) => {
        e.preventDefault()

        $('#submitBtn').html('<i class="fas fa-spinner fa-spin"></i> Uploading ..')
        $('#submitBtn').prop('disabled', true)

        var idsArr = [];

        $('.row_check:checked').each( function() {
            idsArr.push($(this).val())
        })

        var strIds = idsArr.join(',')
        
        console.log(strIds)

        const x = new FormData()
        x.append('title', document.getElementById('title').value)
        x.append('body', document.getElementById('body').value)
        x.append('image', document.getElementById('image').files[0])
        x.append('tags', strIds)
        
        axios.post("{{ route('posts.store') }}", x )
            .then( (response) => {
                console.log(response.data)
                alert(response.data.sms)
                window.location.href = "{{ route('posts.index') }}"
            })

            .catch((error) => {
                $('#submitBtn').html('Submit')
                $('#submitBtn').prop('disabled', false)
                console.log(error.response)
                const errBoxes = document.getElementsByClassName('form-control')
                const errSms = document.getElementsByClassName('invalid-feedback')
                Array.from(errBoxes).forEach(el => el.classList.remove('is-invalid'))
                Array.from(errSms).forEach(el => el.innerHTML = "")
                Array.from(errSms).forEach(el => el.style.display = "none")

                // document.getElementById('smsErr').innerHTML = error.response.data.message
                // document.getElementById('smsErr').classList.add('d-block')

                if (error.response.data.errors.title) {
                    let box = document.querySelector('#title')
                    let sms = document.getElementById('err-title')
                    sms.innerHTML = error.response.data.errors.title[0]
                    sms.style.display = "block"
                    box.classList.add('is-invalid')
                }

                if (error.response.data.errors.body) {
                    let box = document.querySelector('#body')
                    let sms = document.getElementById('err-body')
                    sms.innerHTML = error.response.data.errors.body[0]
                    sms.style.display = "block"
                    box.classList.add('is-invalid')
                }

                if (error.response.data.errors.image) {
                    let box = document.querySelector('#image')
                    let sms = document.getElementById('err-image')
                    sms.innerHTML = error.response.data.errors.image[0]
                    sms.style.display = "block"
                    box.classList.add('is-invalid')
                }

                if (error.response.data.errors.tags) {
                    let box = document.querySelector('#{{ "tag-" . utf8_decode($tag->name) }}')
                    let sms = document.getElementById('err-tags')
                    sms.innerHTML = error.response.data.errors.tags[0]
                    sms.style.display = "block"
                    box.classList.add('is-invalid')
                }
            })
        });
    });
    
</script>
@endsection

resources/views/posts/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <form method="POST" id="editForm" action="" enctype="multipart/form-data">
        {{ csrf_field() }}
        <div class="form-group">
            <label for="title">Post Title</label>
            <input type="text" class="form-control" id="title" name="title" aria-describedby="title-Help" value="{{$post->title}}">
            <div class="invalid-feedback" id="err-title" role="alert"></div>
            <small id="titleHelp" class="form-text text-muted">Title of the post.</small>
        </div>
        <div class="form-group">
            <label for="body">Post Body</label>
            <textarea class="form-control" id="body" name="body" rows="3">{{$post->body}}</textarea>
            <div class="invalid-feedback" id="err-body" role="alert"></div>
            <small id="titleHelp" class="form-text text-muted">Post content.</small>
        </div>
        <div class="form-group">
            <img class="img-fluid" src="{{'/images/posts/' . $post->image}}" alt="">
        </div>
        <div class="form-group">
            <input type="file" id="image" name="image" />
            <div class="invalid-feedback" id="err-image" role="alert"></div>
        </div>
        <div class="form-group row">
                {{-- POST TAGS --}}
                <div class="col-lg-12">
                    <strong class="text-muted mb-3 mt-4 d-block">Tags:</strong>
                    <div class="custom-control custom-checkbox custom-control-inline">
                        <input type="checkbox" id="select_all" class="custom-control-input text-lowercase">
                        <label class="custom-control-label text-uppercase" for="select_all"><strong>select all</strong></label>
                    </div>
                    @foreach( $tags as $tag )
                    <div class="custom-control custom-checkbox custom-control-inline">
                        <input type="checkbox" name="tags" class="custom-control-input text-lowercase row_check"
                            id="{{ "tag-" . utf8_decode($tag->name) }}" value="{{ $tag->id }}" data-id="{{$tag->id}}"
                            @foreach($post->tags as $x)
                                @if ($x->id == $tag->id)
                                        checked
                                @endif
                            @endforeach
                            >
                        <label class="custom-control-label text-lowercase" for="{{ "tag-". utf8_decode($tag->name) }}">
                        {{ utf8_decode($tag->name) }}</label>
                    </div>
                    @endforeach
                    <div class="invalid-feedback" id="err-tags" role="alert"></div>
                </div>
            </div>
        <div class="form-group">
            <a class="btn btn-danger" href="{{URL::previous()}}">Cancel</a>
            <button type="submit" id="submitBtn" class="btn btn-primary">
                {{ __('Submit') }}
            </button>
        </div>
    </form>
</div>

<script>

    $('#select_all').on('click', (e) => {        
        $('.row_check').prop('checked', $(e.target).prop('checked'));
    })

    $('.row_check').on('click', () => {
        if ($('.row_check:checked').length == $('.row_check').length) {
            $('#select_all').prop('checked', true)
        } else {
            $('#select_all').prop('checked', false)
        }
    })

    document.getElementById('editForm').addEventListener('submit', function (e) {

        e.preventDefault()

        $('#submitBtn').html('<i class="fas fa-spinner fa-spin"></i> Loading ..')
        $('#submitBtn').prop('disabled', true)

        var idsArr = [];

        $('.row_check:checked').each( function() {
            idsArr.push($(this).val())
        })

        var strIds = idsArr.join(',')

        console.log(strIds)

        const x = new FormData()
        x.append('title', document.getElementById('title').value)
        x.append('body', document.getElementById('body').value)
        x.append('image', document.getElementById('image').files[0])
        x.append('tags', strIds)
        x.append('_method', 'PUT')

        // console.log(x)

        axios.post("{{ route('posts.update', $post->id) }}", x)
            .then((res) => {
                alert(res.data.sms)
                window.location.href = "{{ route('posts.index') }}"
            })
            .catch((error) => {

                console.log(error.response)

                $('#submitBtn').html("<i class='fas fa-save'></i> Submit")
                $('#submitBtn').prop('disabled', false)
                // $('#cancelUpdate').prop('disabled', false)
                
                const errBoxes = document.getElementsByClassName('form-control')
                const errSms = document.getElementsByClassName('invalid-feedback')
                Array.from(errBoxes).forEach(el => el.classList.remove('is-invalid'))
                Array.from(errSms).forEach(el => el.innerHTML = "")
                Array.from(errSms).forEach(el => el.style.display = "none")

                if (error.response.data.errors.title) {
                    let box = document.querySelector('#title')
                    let sms = document.getElementById('err-title')
                    sms.innerHTML = error.response.data.errors.title[0]
                    sms.style.display = "block"
                    box.classList.add('is-invalid')
                }

                if (error.response.data.errors.body) {
                    let box = document.querySelector('#body')
                    let sms = document.getElementById('err-body')
                    sms.innerHTML = error.response.data.errors.body[0]
                    sms.style.display = "block"
                    box.classList.add('is-invalid')
                }

                if (error.response.data.errors.tags) {
                    let box = document.querySelector('#{{ "tag-" . utf8_decode($tag->name) }}')
                    let sms = document.getElementById('err-tags')
                    sms.innerHTML = error.response.data.errors.tags[0]
                    sms.style.display = "block"
                    box.classList.add('is-invalid')
                }

            })
    });
</script>

@endsection

resources/views/posts/index.blade.php
@extends('layouts.app')

@section('content')

@include('layouts.messages')

<div class="container">

    <div class="input-group mb-3">
        <div class="input-group-prepend">
            <form action="{{route('posts.index')}}" method="GET">
                <button class="btn btn-primary dropdown-toggle" type="button" data-toggle="dropdown"
                aria-haspopup="true" aria-expanded="false">Search By</button>
            <div class="dropdown-menu">
                <a class="dropdown-item" href="#">Title</a>
                <a class="dropdown-item" href="#">Tag</a>
            </div>
        </div>
        <input type="text" class="form-control" name="s" placeholder=" Search..." value="{{ isset($s) ? $s : '' }}">
    </form>
    </div>

    <div class="row">
        @if(count($posts))
        @foreach($posts as $post)
        <div class="col-lg-4 col-md-4">
            <div class="card" style="width: ">
                <img class="card-img-top" src="{{'/images/posts/' . $post->image}}" alt="Card image cap">
                <div class="card-body">
                    <h5 class="card-title">{{$post->title}}</h5>
                    <small>
                        @foreach($post->tags as $x)
                        {{ $x->name }}
                        {{ !$loop->last ? ',' : '' }}
                        @endforeach
                    </small>
                    <br>
                    <small>Date: {{$post->created_at}}</small>
                    <br>
                    <small>By: {{$post->user->name}}</small>
                    <br><br>
                    <p class="card-text">
                        {{$post->body}}
                    </p>
                    <div class="form-group">
                    </div>
                    @can('admin_only', $post)
                    <div class="form-group">
                        <form method="POST" action="{{ route('posts.destroy', $post->id) }}">
                            <a href="{{route('posts.edit', $post->id)}}" class="btn btn-primary">Edit</a>
                            @method('DELETE')
                            @csrf
                            <button type="submit" class="btn btn-danger">Delete</button>
                        </form>
                    </div>
                    @endcan
                </div>
            </div>
        </div>
        @endforeach
        @else
        <p>There is no post at the moment.</p>
        @endif
    </div>
    {{$posts->appends(['s' => $s])->links()}}
</div>
@endsection

resources/views/posts/search.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
        <form action="" method="GET">
            <div class="form-group">
            <input type="text" class="form-control" name="s" placeholder=" Search..." value="{{isset($s) ? : ''}}">
            </div>
            <div class="form-group">
                <button class="btn btn-primary" type="submit">
                    Search
                </button>
            </div>
        </form>
    </div>
        {{-- {{$posts->appends(['s' => $s])->links()}} --}}
@endsection

resources/views/posts/show.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-12 d-flex justify-content-center">
                <div class="card" style="width:50rem;">
                    <img class="card-img-top" src="{{asset('images/posts/' . $post->image)}}" alt="Card image cap">
                    <div class="card-body">
                        <h5 class="card-title">{{$post->title}}</h5>
                        <p class="card-text">{!! html_entity_decode($post->body) !!}</p>
                        {{-- <small class="card-text">By: {{$post->user->name}}</small> --}}
                        <p><small class="card-text">Created On: {{$post->created_at}}</small></p>
                        <a href="{{URL::previous()}}" class="btn btn-primary">Back</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection